# Generated by Django 5.0.8 on 2024-08-20 19:47

import charities.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='reg_number',
            field=models.CharField(max_length=10, validators=[charities.validators.RegNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_benefactor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charities.benefactor'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='gender_limit',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MF', 'Unset')], default='MF', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
